import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect } from 'react'
import { queryClient } from './_app'

const Home: NextPage = () => {
  useEffect(() => {
    queryClient.prefetchQuery('test', () => fetch('/api/hello').then(res => { return res.json() }));
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Crypto Shipto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Crypto Shipto
        </h1>
        <br />
        <span>{process.env.NEXT_PUBLIC_FUN_FACT}</span>

        <p className={styles.description}>
          Visit any one our neat pages and discover the power of Next.JS !
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="/server-props" className={styles.card}>
            <h2>Server Generated Props with API data</h2>
            <p>Fun fact - you are awesome!</p>
          </a>

          <a href="/static-props" className={styles.card}>
            <h2>Staticly Generated Props with API data</h2>
            <p>Fun fact - you are awesome!</p>
          </a>

          <a href="/prefetched-data" className={styles.card}>
            <h2>Prefetched Data with react-query</h2>
            <p>Fun fact - Your body heals itself!</p>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
